### ISSUE TITLE
Name for the bot

### ISSUE THREAD

**Issue by rexim** [tsoding/tsoder#1]
If you have any good ideas please comment them or upvote existing ones.

**Comment by rexim** [comment]
Maybe just call it Tsoding Bot?

**Comment by rexim** [comment]
PHP?

**Comment by rexim** [comment]
Khooy?

**Comment by keddelzz** [comment]
You say tsoding instead of coding, so maybe a cool name might be tsoder?

**Comment by rexim** [comment]
teabot or tbot

**Comment by ForNeVeR** [comment]
I'd propose something from the Russian folklore: Tsarevich, Koshej, Izbushka. Very nice and fun to pronounce for foreign speakers!

**Comment by rexim** [comment]
@ForNeVeR does knooy belong to Russian folklore?

**Comment by ForNeVeR** [comment]
I bet it is. Although I doubt it'll be a good name for the bot.

**Comment by rexim** [comment]
Ok, objectively "tsoder" by the highest amount of votes. Let's roll with it.

**Comment by ForNeVeR** [comment]
I like the outcome. It's a good name.
