### ISSUE TITLE
Integrate urban dictionary with tsoder

### ISSUE THREAD

**Issue by voldyman** [tsoding/tsoder#91]
urban dictionary lookups would be fun in the chat

example.

`!ud farf`

**Comment by rexim** [comment]
Surprisingly, there API is unofficial and not documented properly anywhere. But it is possible to find different bits on the Internet: https://github.com/zdict/zdict/wiki/Urban-dictionary-API-documentation I think we can work with that.

**Comment by rexim** [comment]
- HTTP Client for Erlang: http://erlang.org/doc/apps/inets/http_client.html
- JSON: https://github.com/davisp/jiffy
